/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.devworks.view;

import br.com.devworks.dao.ClientesDAO;
import br.com.devworks.model.Clientes;
import br.com.devworks.model.utilitarios;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luiz
 */
public class CadProd extends javax.swing.JFrame {

    //listando dados da tabela
    public void listar(){
    
    ClientesDAO dao = new ClientesDAO();
    List<Clientes> lista = dao.listarClientes();
        
    DefaultTableModel dados = (DefaultTableModel) tabelaDeClientes.getModel();
    dados.setNumRows(0);
    
    
    for(Clientes c: lista){
        
        dados.addRow(new Object[]{
            c.getId(),
            c.getNome(),
            c.getRg(),
            c.getCpf(),
            c.getEmail(),
            c.getTelefone(),
            c.getCelular(),
            c.getCep(),
            c.getEndereco(),
            c.getNumero(),
            c.getComplemento(),
            c.getBairro(),
            c.getCidade(),
            c.getUf()
                
            
                
        });
    
    }
    
        
    
    }
    public CadProd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelDaTabelaClientes = new javax.swing.JTabbedPane();
        painelDadosPessoais = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoDados = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeDados = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmailDados = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNumeroDados = new javax.swing.JTextField();
        btnPesquisaNomeDadosPessoais = new javax.swing.JButton();
        painelConsultaClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDeClientes = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txtNomeConsultaCliente = new javax.swing.JTextField();
        btnPesquisaCliente = new javax.swing.JToggleButton();
        btnSalvarCadCli = new javax.swing.JButton();
        btnNovoCadCli = new javax.swing.JButton();
        btnExcluirCadCli = new javax.swing.JButton();
        btnEditarCadCli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Codigo: ");

        txtCodigoDados.setEditable(false);
        txtCodigoDados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCodigoDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoDadosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Descrição:");

        txtNomeDados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNomeDados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeDadosKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Quantidade:");

        txtEmailDados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtEmailDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailDadosActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Preço:");

        txtNumeroDados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNumeroDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDadosActionPerformed(evt);
            }
        });

        btnPesquisaNomeDadosPessoais.setText("Pesquisar");
        btnPesquisaNomeDadosPessoais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaNomeDadosPessoaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDadosPessoaisLayout = new javax.swing.GroupLayout(painelDadosPessoais);
        painelDadosPessoais.setLayout(painelDadosPessoaisLayout);
        painelDadosPessoaisLayout.setHorizontalGroup(
            painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomeDados, javax.swing.GroupLayout.DEFAULT_SIZE, 1079, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisaNomeDadosPessoais)
                        .addGap(54, 54, 54))
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmailDados, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumeroDados, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoDados, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        painelDadosPessoaisLayout.setVerticalGroup(
            painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaNomeDadosPessoais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        painelDaTabelaClientes.addTab("Dados pessoais", painelDadosPessoais);

        tabelaDeClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Quantidade", "Descrição", "Preço"
            }
        ));
        tabelaDeClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDeClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaDeClientes);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Nome:");

        txtNomeConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeConsultaClienteActionPerformed(evt);
            }
        });
        txtNomeConsultaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeConsultaClienteKeyPressed(evt);
            }
        });

        btnPesquisaCliente.setText("Pesquisar");
        btnPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelConsultaClientesLayout = new javax.swing.GroupLayout(painelConsultaClientes);
        painelConsultaClientes.setLayout(painelConsultaClientesLayout);
        painelConsultaClientesLayout.setHorizontalGroup(
            painelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeConsultaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(888, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        painelConsultaClientesLayout.setVerticalGroup(
            painelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultaClientesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(painelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addGroup(painelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomeConsultaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisaCliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelDaTabelaClientes.addTab("Consulta de Estoque", painelConsultaClientes);

        btnSalvarCadCli.setText("SALVAR");
        btnSalvarCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadCliActionPerformed(evt);
            }
        });

        btnNovoCadCli.setText("NOVO");
        btnNovoCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCadCliActionPerformed(evt);
            }
        });

        btnExcluirCadCli.setText("EXCLUIR");
        btnExcluirCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCadCliActionPerformed(evt);
            }
        });

        btnEditarCadCli.setText("EDITAR");
        btnEditarCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCadCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelDaTabelaClientes)
            .addGroup(layout.createSequentialGroup()
                .addGap(517, 517, 517)
                .addComponent(btnNovoCadCli)
                .addGap(18, 18, 18)
                .addComponent(btnSalvarCadCli)
                .addGap(18, 18, 18)
                .addComponent(btnEditarCadCli)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirCadCli)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(painelDaTabelaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarCadCli)
                    .addComponent(btnExcluirCadCli)
                    .addComponent(btnSalvarCadCli)
                    .addComponent(btnNovoCadCli))
                .addGap(37, 37, 37))
        );

        setSize(new java.awt.Dimension(1400, 663));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDadosActionPerformed

    private void txtEmailDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailDadosActionPerformed

    private void txtNomeConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeConsultaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeConsultaClienteActionPerformed

    private void txtNumeroDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDadosActionPerformed

    private void btnSalvarCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadCliActionPerformed
        // TODO add your handling code here:

        try {

            Clientes obj = new Clientes();
            obj.setNome(txtNomeDados.getText());
            obj.setRg(txtRgDados.getText());
            obj.setCpf(txtCpfDados.getText());
            obj.setEmail(txtEmailDados.getText());
            obj.setTelefone(txtTelefonedados.getText());
            obj.setCelular(txtCelularDados.getText());
            obj.setCep(txtCepDados.getText());
            obj.setEndereco(txtEnderecoDados.getText());
            obj.setNumero(Integer.parseInt(txtNumeroDados.getText()));
            obj.setComplemento(txtComplementoDados.getText());
            obj.setBairro(txtBairroDados.getText());
            obj.setCidade(txtCidadeDados.getText());
            obj.setUf(comboUfDados.getSelectedItem().toString());
            
            ClientesDAO dao = new ClientesDAO();
            dao.cadastrarCliente(obj);
                        new utilitarios().LimpaTela(painelDadosPessoais);


        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);

        }


    }//GEN-LAST:event_btnSalvarCadCliActionPerformed

    private void btnNovoCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCadCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoCadCliActionPerformed

    private void btnExcluirCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCadCliActionPerformed
                try {
                  Clientes obj = new Clientes();

                 obj.setId(Integer.parseInt(txtCodigoDados.getText()));
                      ClientesDAO dao = new ClientesDAO();
                      dao.excluirCliente(obj);
            new utilitarios().LimpaTela(painelDadosPessoais);

            
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnExcluirCadCliActionPerformed

    private void btnEditarCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCadCliActionPerformed
        // TODO add your handling code here:
        

        try {

            Clientes obj = new Clientes();
            obj.setNome(txtNomeDados.getText());
            obj.setRg(txtRgDados.getText());
            obj.setCpf(txtCpfDados.getText());
            obj.setEmail(txtEmailDados.getText());
            obj.setTelefone(txtTelefonedados.getText());
            obj.setCelular(txtCelularDados.getText());
            obj.setCep(txtCepDados.getText());
            obj.setEndereco(txtEnderecoDados.getText());
            obj.setNumero(Integer.parseInt(txtNumeroDados.getText()));
            obj.setComplemento(txtComplementoDados.getText());
            obj.setBairro(txtBairroDados.getText());
            obj.setCidade(txtCidadeDados.getText());
            obj.setUf(comboUfDados.getSelectedItem().toString());
            obj.setId(Integer.parseInt(txtCodigoDados.getText()));
            
            ClientesDAO dao = new ClientesDAO();
            dao.alterarCliente(obj);
            new utilitarios().LimpaTela(painelDadosPessoais);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);

        }
    }//GEN-LAST:event_btnEditarCadCliActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       ///caregar a lista
       listar();
        
    }//GEN-LAST:event_formWindowActivated

    private void tabelaDeClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDeClientesMouseClicked
        // passar dados da tabela para o painel de Dados Pessoais
        painelDaTabelaClientes.setSelectedIndex(0);
        txtCodigoDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
                .getSelectedRow(), 0).toString());
        
        txtNomeDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
                .getSelectedRow(), 1).toString());
        txtRgDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
                .getSelectedRow(), 2).toString());
        txtCpfDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
                .getSelectedRow(), 3).toString());
        txtEmailDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
                .getSelectedRow(), 4).toString());
        txtTelefonedados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
                .getSelectedRow(), 5).toString());
        txtCelularDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
                .getSelectedRow(), 6).toString());
        txtCepDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
                .getSelectedRow(), 7).toString());
        txtEnderecoDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
                .getSelectedRow(), 8).toString());
        txtNumeroDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
                .getSelectedRow(), 9).toString());
        txtComplementoDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
                .getSelectedRow(), 10).toString());
        txtBairroDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
                .getSelectedRow(), 11).toString());
        txtCidadeDados.setText(tabelaDeClientes.getValueAt(tabelaDeClientes
                .getSelectedRow(), 12).toString());
        comboUfDados.setSelectedItem(tabelaDeClientes.getValueAt(tabelaDeClientes
                .getSelectedRow(), 13).toString());
        
        
    }//GEN-LAST:event_tabelaDeClientesMouseClicked

    private void btnPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaClienteActionPerformed
        // Botao pesquisar na tabela de clientes
        
        String nome = "%"+txtNomeConsultaCliente.getText()+"%";
         ClientesDAO dao = new ClientesDAO();
    List<Clientes> lista = dao.buscaClientePorNome(nome);
        
    DefaultTableModel dados = (DefaultTableModel) tabelaDeClientes.getModel();
    dados.setNumRows(0);
    
    
    for(Clientes c: lista){
        
        dados.addRow(new Object[]{
            c.getId(),
            c.getNome(),
            c.getRg(),
            c.getCpf(),
            c.getEmail(),
            c.getTelefone(),
            c.getCelular(),
            c.getCep(),
            c.getEndereco(),
            c.getNumero(),
            c.getComplemento(),
            c.getBairro(),
            c.getCidade(),
            c.getUf()
                
            
                
        });
    }
    }//GEN-LAST:event_btnPesquisaClienteActionPerformed

    private void txtNomeConsultaClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeConsultaClienteKeyPressed
        // Pesquisa enquanto digita
         String nome = "%"+txtNomeConsultaCliente.getText()+"%";
         ClientesDAO dao = new ClientesDAO();
    List<Clientes> lista = dao.buscaClientePorNome(nome);
        
    DefaultTableModel dados = (DefaultTableModel) tabelaDeClientes.getModel();
    dados.setNumRows(0);
    
    
    for(Clientes c: lista){
        
        dados.addRow(new Object[]{
            c.getId(),
            c.getNome(),
            c.getRg(),
            c.getCpf(),
            c.getEmail(),
            c.getTelefone(),
            c.getCelular(),
            c.getCep(),
            c.getEndereco(),
            c.getNumero(),
            c.getComplemento(),
            c.getBairro(),
            c.getCidade(),
            c.getUf()
                
            
                
        });
    }
    }//GEN-LAST:event_txtNomeConsultaClienteKeyPressed

    private void btnPesquisaNomeDadosPessoaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaNomeDadosPessoaisActionPerformed
        // Pesquisar na tela dados pessoais
        try {
            String nome = txtNomeDados.getText();
            Clientes obj = new Clientes();
            ClientesDAO dao = new ClientesDAO();
            
            obj = dao.consultaPorNome(nome);
            if(obj.getNome() != null){
            txtCodigoDados.setText(String.valueOf(obj.getId()));
            
               txtNomeDados.setText(obj.getNome());
        txtRgDados.setText(obj.getRg());
        txtCpfDados.setText(obj.getCpf());
        txtEmailDados.setText(obj.getEmail());
        txtTelefonedados.setText(obj.getTelefone());
        txtCelularDados.setText(obj.getCelular());
        txtCepDados.setText(obj.getCep());
        txtEnderecoDados.setText(obj.getEndereco());
        txtNumeroDados.setText(Integer.toString(obj.getNumero()));
        txtComplementoDados.setText(obj.getComplemento());
        txtBairroDados.setText(obj.getBairro());
        txtCidadeDados.setText(obj.getCidade());
        comboUfDados.setSelectedItem(obj.getUf());
            }else{
            JOptionPane.showMessageDialog(null, "CLIENTE NÃO ENCONTRADO");
            
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
           
    }//GEN-LAST:event_btnPesquisaNomeDadosPessoaisActionPerformed

    private void txtNomeDadosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeDadosKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
        try {
            String nome = txtNomeDados.getText();
            Clientes obj = new Clientes();
            ClientesDAO dao = new ClientesDAO();
            
            obj = dao.consultaPorNome(nome);
            if(obj.getNome() != null){
            txtCodigoDados.setText(String.valueOf(obj.getId()));
            
               txtNomeDados.setText(obj.getNome());
        txtRgDados.setText(obj.getRg());
        txtCpfDados.setText(obj.getCpf());
        txtEmailDados.setText(obj.getEmail());
        txtTelefonedados.setText(obj.getTelefone());
        txtCelularDados.setText(obj.getCelular());
        txtCepDados.setText(obj.getCep());
        txtEnderecoDados.setText(obj.getEndereco());
        txtNumeroDados.setText(Integer.toString(obj.getNumero()));
        txtComplementoDados.setText(obj.getComplemento());
        txtBairroDados.setText(obj.getBairro());
        txtCidadeDados.setText(obj.getCidade());
        comboUfDados.setSelectedItem(obj.getUf());
            }else{
            JOptionPane.showMessageDialog(null, "CLIENTE NÃO ENCONTRADO");
            
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
       
       }
    }//GEN-LAST:event_txtNomeDadosKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarCadCli;
    private javax.swing.JButton btnExcluirCadCli;
    private javax.swing.JButton btnNovoCadCli;
    private javax.swing.JToggleButton btnPesquisaCliente;
    private javax.swing.JButton btnPesquisaNomeDadosPessoais;
    private javax.swing.JButton btnSalvarCadCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelConsultaClientes;
    private javax.swing.JTabbedPane painelDaTabelaClientes;
    private javax.swing.JPanel painelDadosPessoais;
    private javax.swing.JTable tabelaDeClientes;
    private javax.swing.JTextField txtCodigoDados;
    private javax.swing.JTextField txtEmailDados;
    private javax.swing.JTextField txtNomeConsultaCliente;
    private javax.swing.JTextField txtNomeDados;
    private javax.swing.JTextField txtNumeroDados;
    // End of variables declaration//GEN-END:variables
}
